### ISSUE TITLE
Random crash while walking around the world

### ISSUE THREAD

**Issue by GustavoJadson** [IsaiahPatton/thallium#6]
Game crashes after I create/load a world and walk around.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 8/3/20 7:36 PM
Description: Exception while ticking

java.lang.IllegalStateException: Should always be able to create a chunk!
	at net.minecraft.class_1937.method_8402(class_1937.java:253)
	at net.minecraft.class_4538.method_22342(class_4538.java:128)
	at net.minecraft.class_1937.method_8497(class_1937.java:246)
	at net.minecraft.class_1937.method_8320(class_1937.java:450)
	at net.minecraft.class_2397.method_10300(class_2397.java:77)
	at net.minecraft.class_2397.method_9588(class_2397.java:55)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:873)
	at net.minecraft.class_3218.method_14189(class_3218.java:596)
	at net.minecraft.class_1949.method_8670(class_1949.java:84)
	at net.minecraft.class_3218.method_18765(class_3218.java:351)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1937.method_8402(class_1937.java:253)
	at net.minecraft.class_4538.method_22342(class_4538.java:128)
	at net.minecraft.class_1937.method_8497(class_1937.java:246)
	at net.minecraft.class_1937.method_8320(class_1937.java:450)
	at net.minecraft.class_2397.method_10300(class_2397.java:77)
	at net.minecraft.class_2397.method_9588(class_2397.java:55)
	at net.minecraft.class_4970$class_4971.method_26192(class_4970.java:873)
	at net.minecraft.class_3218.method_14189(class_3218.java:596)

-- Block being ticked --
Details:
	Block location: World: (191,84,-6), Chunk: (at 15,5,10 in 11,-1; contains blocks 176,0,-16 to 191,255,-1), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.class_1949.method_8670(class_1949.java:84)
	at net.minecraft.class_3218.method_18765(class_3218.java:351)

-- Affected level --
Details:
	All players: 1 total; [class_3222['GameJadson'/216, l='ServerLevel[New World]', x=136.70, y=71.42, z=10.80]]
	Chunk stats: ServerChunkCache: V=2082,T=314
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,5), Chunk: (at 0,4,5 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 2111 game time, 2111 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 149604 (now: false), thunder time: 159192 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813)
	at net.minecraft.class_1132.method_3748(class_1132.java:93)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Linux (amd64) version 5.4.0-42-generic
	Java Version: 1.8.0_262, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 987351608 bytes (941 MB) / 1718616064 bytes (1639 MB) up to 3029336064 bytes (2889 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms800m -Xmx3250m
	Player Count: 1 / 8; [class_3222['GameJadson'/216, l='ServerLevel[New World]', x=136.70, y=71.42, z=10.80]]
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'
#@!@# Game crashed! Crash report saved to: #@!@# /home/gamejadson/.local/share/multimc/instances/1.16.1/.minecraft/crash-reports/crash-2020-08-03_19.36.29-server.txt
[19:36:29] [Server thread/INFO]: Stopping singleplayer server as player logged out
[19:36:29] [Server thread/INFO]: Saving worlds
[19:36:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by IsaiahPatton** [comment]
fixed in version 1.5
